### ISSUE TITLE
Logs ?

### ISSUE THREAD

**Issue by HydrelioxGitHub** [rubenpeters91/rgb2mqtt#7]
Hello, 
I would like to use your work. But after following the instruction ( install pip , then run config, then run the script), I can't see anything happen. Can you provide where is stored the configuration file, or if there are logs somewhere that I can find where is the problem ?

Thank you for your skills and your time.

**Comment by rubenpeters91** [comment]
Thanks for trying out this tool, I'd love to help.

Bot the config and the logs are written to the AppData folder on Windows, or your home folder on Linux/Mac
To find the AppData folder you can type `%appdata%` in Windows explorer and it should be under `AppData\Roaming\rgb2mqtt\`

Let me know if I can help any further!

**Comment by HydrelioxGitHub** [comment]
I've found the folder but it's all empty. Should the conf file be here too ?

Thanks for your time.

**Comment by rubenpeters91** [comment]
Yeah it should, but looking back at the code I found a bug 😬, which has now been solved in version 1.0.1 (see #8)
Could you try reinstalling with `pip install --upgrade rgb2mqtt` and running the scripts again?

I also added a -v option to rgb2mqtt-run, (`rgb2mqtt-run -v`) which prints the logs in the terminal instead of in the logfile

**Comment by HydrelioxGitHub** [comment]
Better result, the config file is written is the folder. But nothing more when I run the script.
![image](https://github.com/rubenpeters91/rgb2mqtt/assets/15862735/dc43ef53-42ff-4b88-a547-6afb766d6de6)

**Comment by rubenpeters91** [comment]
Yeah that makes sense, the rgb2mqtt-run command is a gui script, so it will run in the background on Windows. I've changed the script to be a console script in the latest version (1.1.0 see: #9 ), so please update the package with `pip install --upgrade rgb2mqtt` and rerun `rgb2mqtt-run -v` which should now print errors and logs directly to the terminal.

You're probably running into issues with connecting with openRGB server or MQTT, I'm planning on adding some more documentation soon but in the meantime:

- Make sure openRGB is running and you can control your RGB's through openRGB. Also make sure the SDK server is running (you can auto-start the server in the Settings of openRGB)
- Make sure your mqtt server is running and reachable (are you using Mosquitto broker through Home Assistant?)
